//==================================================
//POV-Ray Materials list
//==================================================
//This file has been created by PoseRay v3.8.18.390
//3D model to POV-Ray/Moray Converter.
//Author: FlyerX
//Email: flyerx_2000@yahoo.com
//Web: http://mysite.verizon.net/sfg0000/
//==================================================
//Files needed to run the POV-Ray scene:
//Dreadnought_POV_main.ini (initialization file - open this to render)
//Dreadnought_POV_scene.pov (scene setup of cameras, lights and geometry)
//Dreadnought_POV_geom.inc (geometry mesh)
//Dreadnought_POV_mat.inc (materials)
// 
 
 
//==================================================
//Map definitions
 
//==================================================
//Material definitions
#declare MATERIAL0_= HTX;
//==================================================
#declare MATERIAL1_= HTX;
//==================================================
#declare MATERIAL2_= HTX;
#declare MATERIAL3_= HTX;
#declare MATERIAL4_= HTX;
#declare MATERIAL5_= MTX;
#declare MATERIAL6_= CTX;
#declare MATERIAL7_= CTX;
#declare MATERIAL8_= CTX;
#declare MATERIAL9_= CTX;
#declare MATERIAL10_= CTX;
#declare MATERIAL11_= CTX;
#declare MATERIAL12_= CTX;
#declare MATERIAL13_= CTX;
#declare MATERIAL14_= CTX;
#declare MATERIAL15_= CTX;
