//==================================================
//POV-Ray Materials list
//==================================================
//This file has been created by PoseRay v3.8.18.390
//3D model to POV-Ray/Moray Converter.
//Author: FlyerX
//Email: flyerx_2000@yahoo.com
//Web: http://mysite.verizon.net/sfg0000/
//==================================================
//Files needed to run the POV-Ray scene:
//ED-209_POV_main.ini (initialization file - open this to render)
//ED-209_POV_scene.pov (scene setup of cameras, lights and geometry)
//ED-209_POV_geom.inc (geometry mesh)
//ED-209_POV_mat.inc (materials)
// 
 
 
//==================================================
//Map definitions
 
//==================================================
//Material definitions
#declare MATERIAL0_= HTX;
#declare MATERIAL1_= MTX;
#declare MATERIAL2_= HTX;
#declare MATERIAL3_= CTX;
#declare MATERIAL4_= CTX;
#declare MATERIAL5_= CTX;
#declare MATERIAL6_= CTX;
#declare MATERIAL7_= CTX;
#declare MATERIAL8_= CTX;
