//==================================================
//POV-Ray Materials list
//==================================================
//This file has been created by PoseRay v3.10.3.412
//3D model to POV-Ray/Moray Converter.
//Author: FlyerX
//Email: flyerx_2000@yahoo.com
//Web: http://mysite.verizon.net/sfg0000/
//==================================================
//Files needed to run the POV-Ray scene:
//mynewship_POV_main.ini (initialization file - open this to render)
//mynewship_POV_scene.pov (scene setup of cameras, lights and geometry)
//mynewship_POV_geom.inc (geometry mesh)
//mynewship_POV_mat.inc (materials)
// 
 
#include "stdinc.inc"
 
//==================================================
//Map definitions
 
//==================================================
//Material definitions
#declare Default_= MTX;
