//==================================================
//POV-Ray Materials list
//==================================================
//This file has been created by PoseRay v3.8.18.390
//3D model to POV-Ray/Moray Converter.
//Author: FlyerX
//Email: flyerx_2000@yahoo.com
//Web: http://mysite.verizon.net/sfg0000/
//==================================================
//Files needed to run the POV-Ray scene:
//final_POV_main.ini (initialization file - open this to render)
//final_POV_scene.pov (scene setup of cameras, lights and geometry)
//final_POV_geom.inc (geometry mesh)
//final_POV_mat.inc (materials)
// 
 
 
//==================================================
//Map definitions
 
//==================================================
//Material definitions
#declare _01___Default_= MTX;

//==================================================
