//==================================================
//POV-Ray Materials list
//==================================================
//This file has been created by PoseRay v3.8.18.390
//3D model to POV-Ray/Moray Converter.
//Author: FlyerX
//Email: flyerx_2000@yahoo.com
//Web: http://mysite.verizon.net/sfg0000/
//==================================================
//Files needed to run the POV-Ray scene:
//product_POV_main.ini (initialization file - open this to render)
//product_POV_scene.pov (scene setup of cameras, lights and geometry)
//product_POV_geom.inc (geometry mesh)
//product_POV_mat.inc (materials)
// 
 
 
//==================================================
//Map definitions
 
//==================================================
//Material definitions
#declare material04_= MTX;
#declare material03_= CTX;
#declare material02_= HTX;
#declare material01_= MTX;
#declare ___default____= HTX;
