// Persistence Of Vision Scene file.
// Generated by Ani2Pov v0.39.
//#declare Show_AxisMarker = 1;
#include "gearhead.inc"
#include "btr_zwar.inc"

object {
   object01
   matrix <1.000000, 0.000000, 0.000000,
          0.000000, 1.000000, 0.000000,
          0.000000, 0.000000, 1.000000,
          0.000000, 0.000000, 0.000000>
   translate <0.000000, 0.000000, 0.000000>
   scale <1.000000, 1.000000, 1.000000>
   scale 1.75
   rotate y * -45
	rotate y * clock * 360
}
