set ImgPath=D:\POVray Images
convert "%ImgPath%\wall_shadow00.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow00_crop.png"
convert "%ImgPath%\wall_shadow01.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow01_crop.png"
convert "%ImgPath%\wall_shadow02.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow02_crop.png"
convert "%ImgPath%\wall_shadow03.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow03_crop.png"
convert "%ImgPath%\wall_shadow04.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow04_crop.png"
convert "%ImgPath%\wall_shadow05.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow05_crop.png"
convert "%ImgPath%\wall_shadow06.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow06_crop.png"
convert "%ImgPath%\wall_shadow07.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow07_crop.png"
convert "%ImgPath%\wall_shadow08.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow08_crop.png"
convert "%ImgPath%\wall_shadow09.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow09_crop.png"
convert "%ImgPath%\wall_shadow10.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow10_crop.png"
convert "%ImgPath%\wall_shadow11.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow11_crop.png"
convert "%ImgPath%\wall_shadow12.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow12_crop.png"
convert "%ImgPath%\wall_shadow13.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow13_crop.png"
convert "%ImgPath%\wall_shadow14.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow14_crop.png"
convert "%ImgPath%\wall_shadow15.png" -background transparent -crop 64x96+0+32! "PNG32:%ImgPath%\wall_shadow15_crop.png"
montage "%ImgPath%\wall_shadow00_crop.png" "%ImgPath%\wall_shadow01_crop.png" "%ImgPath%\wall_shadow02_crop.png" "%ImgPath%\wall_shadow03_crop.png" "%ImgPath%\wall_shadow04_crop.png" "%ImgPath%\wall_shadow05_crop.png" "%ImgPath%\wall_shadow06_crop.png" "%ImgPath%\wall_shadow07_crop.png" "%ImgPath%\wall_shadow08_crop.png" "%ImgPath%\wall_shadow09_crop.png" "%ImgPath%\wall_shadow10_crop.png" "%ImgPath%\wall_shadow11_crop.png" "%ImgPath%\wall_shadow12_crop.png" "%ImgPath%\wall_shadow13_crop.png" "%ImgPath%\wall_shadow14_crop.png" "%ImgPath%\wall_shadow15_crop.png" -background transparent -geometry 64x96! "PNG32:%ImgPath%\wall_shadow.png"
del "%ImgPath%\wall_shadow00_crop.png"
del "%ImgPath%\wall_shadow01_crop.png"
del "%ImgPath%\wall_shadow02_crop.png"
del "%ImgPath%\wall_shadow03_crop.png"
del "%ImgPath%\wall_shadow04_crop.png"
del "%ImgPath%\wall_shadow05_crop.png"
del "%ImgPath%\wall_shadow06_crop.png"
del "%ImgPath%\wall_shadow07_crop.png"
del "%ImgPath%\wall_shadow08_crop.png"
del "%ImgPath%\wall_shadow09_crop.png"
del "%ImgPath%\wall_shadow10_crop.png"
del "%ImgPath%\wall_shadow11_crop.png"
del "%ImgPath%\wall_shadow12_crop.png"
del "%ImgPath%\wall_shadow13_crop.png"
del "%ImgPath%\wall_shadow14_crop.png"
del "%ImgPath%\wall_shadow15_crop.png"
