//==================================================
//POV-Ray Materials list
//==================================================
//This file has been created by PoseRay v3.8.18.390
//3D model to POV-Ray/Moray Converter.
//Author: FlyerX
//Email: flyerx_2000@yahoo.com
//Web: http://mysite.verizon.net/sfg0000/
//==================================================
//Files needed to run the POV-Ray scene:
//ara_kojedo_POV_main.ini (initialization file - open this to render)
//ara_kojedo_POV_scene.pov (scene setup of cameras, lights and geometry)
//ara_kojedo_POV_geom.inc (geometry mesh)
//ara_kojedo_POV_mat.inc (materials)
// 
 
 
//==================================================
//Map definitions
 
//==================================================
//Material definitions
#declare ACAD_color_174_= 
texture{pigment {color rgb <0,0,0.505882352941176> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_174_= MTX;
//==================================================
#declare ACAD_color_81_= 
texture{pigment {color rgb <0.749019607843137,1,0.666666666666667> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_81_= HTX;
//==================================================
#declare ACAD_color_212_= 
texture{pigment {color rgb <0.741176470588235,0,0.741176470588235> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_212_= HTX;
//==================================================
#declare ACAD_color_132_= 
texture{pigment {color rgb <0,0.741176470588235,0.741176470588235> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_132_= MTX;
//==================================================
#declare ACAD_color_112_= 
texture{pigment {color rgb <0,0.741176470588235,0.368627450980392> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_112_= MTX;
//==================================================
#declare ACAD_color_11_= 
texture{pigment {color rgb <1,0.666666666666667,0.666666666666667> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_11_= HTX;
//==================================================
#declare ACAD_color_114_= 
texture{pigment {color rgb <0,0.505882352941176,0.250980392156863> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_114_= HTX;
//==================================================
#declare ACAD_color_253_= 
texture{pigment {color rgb <0.509803921568627,0.509803921568627,0.509803921568627> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_253_= HTX;
//==================================================
#declare ACAD_color_232_= 
texture{pigment {color rgb <0.741176470588235,0,0.368627450980392> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_232_= HTX;
//==================================================
#declare ACAD_color_9_= 
texture{pigment {color rgb <0.501960784313725,0.501960784313725,0.501960784313725> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_9_= HTX;
//==================================================
#declare ACAD_color_121_= 
texture{pigment {color rgb <0.666666666666667,1,0.917647058823529> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_121_= MTX;
//==================================================
#declare ACAD_color_171_= 
texture{pigment {color rgb <0.666666666666667,0.666666666666667,1> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_171_= HTX;
//==================================================
#declare ACAD_color_250_= 
texture{pigment {color rgb <0.2,0.2,0.2> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_250_= HTX;
//==================================================
#declare ACAD_color_194_= 
texture{pigment {color rgb <0.250980392156863,0,0.505882352941176> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_194_= MTX;
//==================================================
#declare ACAD_color_191_= 
texture{pigment {color rgb <0.831372549019608,0.666666666666667,1> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_191_= HTX;
//==================================================
#declare ACAD_color_52_= 
texture{pigment {color rgb <0.741176470588235,0.741176470588235,0> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_52_= MTX;
//==================================================
#declare ACAD_color_111_= 
texture{pigment {color rgb <0.666666666666667,1,0.831372549019608> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_111_= HTX;
//==================================================
#declare ACAD_color_144_= 
texture{pigment {color rgb <0,0.376470588235294,0.505882352941176> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_144_= MTX;
//==================================================
#declare ACAD_color_152_= 
texture{pigment {color rgb <0,0.368627450980392,0.741176470588235> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_152_= HTX;
//==================================================
#declare ACAD_color_13_= 
texture{pigment {color rgb <0.741176470588235,0.494117647058824,0.494117647058824> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_13_= CTX;
//==================================================
#declare ACAD_color_154_= 
texture{pigment {color rgb <0,0.250980392156863,0.505882352941176> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_154_= HTX;
//==================================================
#declare ACAD_color_192_= 
texture{pigment {color rgb <0.368627450980392,0,0.741176470588235> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_192_= HTX;
//==================================================
#declare ACAD_color_14_= 
texture{pigment {color rgb <0.505882352941176,0,0> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_14_= HTX;
//==================================================
#declare ACAD_color_204_= 
texture{pigment {color rgb <0.376470588235294,0,0.505882352941176> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_204_= HTX;
//==================================================
#declare ACAD_color_231_= 
texture{pigment {color rgb <1,0.666666666666667,0.831372549019608> transmit  0} 
        finish{phong 0.2980392 phong_size 36.25229 diffuse 0.6*1 ambient rgb <0,0,0> reflection{0 }}}
#declare ACAD_color_231_= HTX;
//==================================================
