// Persistence Of Vision Scene file.
// Generated by Ani2Pov v0.37.
#include "colors.inc"
#include "GearHead.inc"
#include "monster_urchin.inc"


object {
   object01
   matrix <0.707112, 0.000000, -0.707101,
          0.000000, 1.000000, 0.000000,
          0.707101, 0.000000, 0.707112,
          0.000000, 0.000000, 0.000000>
   translate <0.000000, 0.000000, 0.000000>
   scale <1.000000, 1.000000, 1.000000>
   	scale 3/5
	scale Scale_Mecha
	scale 1/3
	rotate y * -90
	rotate y * clock * 360
}
